apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  root-password: {{ .Values.database.env.MYSQL_ROOT_PASSWORD | b64enc }}
  username: {{ .Values.database.env.MYSQL_USERNAME | b64enc }}
  password: {{ .Values.database.env.MYSQL_PASSWORD | b64enc }}
