apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: exam
type: Opaque
data:
  root-password: Y2hhaW1hMjAwMw== # Encodé en base64
  username: cm9vdA== # Encodé en base64
  password: Y2hhaW1hMjAwMw== # Encodé en base64
