apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database-statefulset
  namespace: exam
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  serviceName: "database-service"
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: mysql:8.0.40-debian
          ports:
            - containerPort: 3306
          resources:
            limits:
              cpu: "500m"
              memory: "500Mi"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: root-password
            - name: MYSQL_DATABASE
              value: "travelo_db"
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            exec:
              command:
                - mysqladmin
                - ping
            initialDelaySeconds: 15
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 500Mi
